Uprade to Play 2.5.10 (#15356)
* Bump the versions to use play 2.5

* Turns out we need springframework as a dependency otherwise we get NoClassDefFoundError with play 2.5...

* General api changes

* Play Filter changes

* Play WS API changes

* Akka stream changes

* upgrading play google oauth

* rename loggers

* Content-type handling changes

* CSRF changes

* use the play default: Dependency injected router

* fix tests: empty parameter key

* fix identity tests

* Fix merging mistakes

* NingWSClient -> AhcWSClient and add WithMaterializer trait

* Fix tests: Make Tests vals that depends on WSClient lazy

App needs to be instantiated before WSClient can be created.
Making the vals lazy to make sure an App is around when the WSClient is
instanciated

* Fix merging issues related to OAuthLoginController

* WSClient withRequestTimeout takes a duration as parameter

* Add missing WithMaterializer trait to football tests

* HttpRecorder: change NingWSResponse into ACHResponse

* Enable deprecation warnings (delete this commit)

* Add missing imports in tests

* Fix rebasing issues

* Merge and fix conflicts

* Bump the versions to use play 2.5

* Play Filter changes

* Play WS API changes

* Akka stream changes

* upgrading play google oauth

* Turns out we need springframework as a dependency otherwise we get NoClassDefFoundError with play 2.5...

* General api changes

* rename loggers

* Content-type handling changes

* CSRF changes

* use the play default: Dependency injected router

* fix tests: empty parameter key

* fix identity tests

* Fix merging mistakes

* NingWSClient -> AhcWSClient and add WithMaterializer trait

* Enable deprecation warnings (delete this commit)

* Fix tests: Make Tests vals that depends on WSClient lazy

App needs to be instantiated before WSClient can be created.
Making the vals lazy to make sure an App is around when the WSClient is
instanciated

* Fix merging issues related to OAuthLoginController

* WSClient withRequestTimeout takes a duration as parameter

* Add missing WithMaterializer trait to football tests

* HttpRecorder: change NingWSResponse into ACHResponse

* Add missing imports in tests

* Fix rebasing issues

* Merge and fix conflicts

* Update play-googleauth to 0.6.0

* CSRFAddToken and CSRFCheck object are deprecated

* Remove deprecated Play.api.Crypto packages

See https://www.playframework.com/documentation/2.5.x/CryptoMigration25
for more info about Crypto migration for Play 2.5
We only use Crypto to encrypt/decrypt cookie values (using AES
algorithm), which are relatively simple operations that can simply be
built using javax.crypto primitives
Therefore I have extracted the 2 methods (encryptAES and decryptAES)
into our own Crypto object.
Given our simple use case I don't feel like adding a complex 3rd-party
dependency like Kalium and Keyczar is required

* Address some sbt warnings

* Workaround for Play 2.5 query string bug

* Fix alignment

* Upgrade to Play 2.5.10

* Use targeting-client version targeting Play 2.5