Scala 2.13: Call augmentString to convert String to StringOps
We are trying to call `toIntOption`, a method of `StringOps` on a `String` so we're getting the error:

```
value toIntOption is not a member of String
```

Normally, we would expect implicit conversions to have worked and change String to StringOps but in this case they don't and we're getting:

```
[error] Note that implicit conversions are not applicable because they are ambiguous:
[error]  both method augmentString in object Predef of type (x: String): scala.collection.StringOps
[error]  and method String2ToOptions in trait Strings of type (s: String): common.package.String2ToOptions
[error]  are possible conversion functions from x$4.type to ?{def toIntOption: ?}
```

So we have to explictly call `augmentString()` to trun `String` to `StringOps` and have access to `toIntOption` method.

Co-authored-by: Roberto Tyley <roberto.tyley@guardian.co.uk>