Use linesIterator on String instead of lines on a WrappedString
`lines` is not a method of `WrappedString` anymore but we can call `linesIterator` on a String after it has been undeprecated in this PR: https://github.com/scala/scala/pull/7269

This way we get rid of the following error:

```
[error] /Users/Ioanna_Kokkini/Projects/frontend/common/app/common/TrailsToShowcase.scala:509:46: value lines is not a member of scala.collection.immutable.WrappedString
[error]     val lines = new WrappedString(trailText).lines.toSeq
[error]                                              ^
[error] one error found
```