Fix broken Facebook client test, providing a sample response for API v3.2
The build of https://github.com/guardian/frontend/pull/21351 failed:

https://teamcity.gutools.co.uk/viewLog.html?buildId=306822&tab=buildResultsDiv&buildTypeId=dotcom_master

with this test failure:

```
FacebookGraphApiTest.should return a valid share count 

java.lang.IllegalStateException: Data file has not been checked in for:
https://graph.facebook.com/v3.2?id=http%3A%2F%2Fwww.theguardian.com%2Fworld%2F2016%2Fdec%2F30%2Feight-charts-that-show-2016-wasnt-as-bad-as-you-think&fields=engagement - /v3.2id=http://www.theguardian.com/world/2016/dec/30/eight-charts-that-show-2016-wasnt-as-bad-as-you-think&fields=engagement,
file: a5ad44ffbe1148f62f924f41827039431d33ac06321c2df29e307703cd8510f4,
headers:
```

...it turns out that `FacebookGraphApiTest` doesn't directly hit the
Facebook API during execution - it uses a stored copy of the Facebook API
response (which has some benefits- it's faster, provides a helpful sample
response, and means our tests aren't dependent on having a network
connection, valid Facebook credentials or even Facebook's API actually
being up) - so we gotta check in a new sample response for Facebook API
v3.2.

Sample response obtained from:

https://developers.facebook.com/tools/explorer/180444840287?method=GET&path=%3Fid%3Dhttp%253A%252F%252Fwww.theguardian.com%252Fworld%252F2016%252Fdec%252F30%252Feight-charts-that-show-2016-wasnt-as-bad-as-you-think%26fields%3Dengagement%20-%20%2Fv3.2id%3Dhttp%3A%2F%2Fwww.theguardian.com%2Fworld%2F2016%2Fdec%2F30%2Feight-charts-that-show-2016-wasnt-as-bad-as-you-think%26fields%3Dengagement&version=v3.2