Upgrade jackson.dataformat lib
Fixing following issue:
"Error while adding Logback Kinesis appender:
com.amazonaws.AmazonClientException: Unable to marshall request to JSON:
Jackson jackson-core/jackson-dataformat-cbor incompatible library
version detected"
This is due to an incompatible version of jackson-dataformat-cbor
(v2.6.7) and jackson-core (v2.8.9) which kinesis-logback-appender
depends on.