Exclude Jackson Core From `logstash-logback-encoder`
In order to avoid conflicts with Play's Jackson dependency and fix error:

```
com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.14.3 requires Jackson Databind version >= 2.14.0 and < 2.15.0 - Found jackson-databind version 2.17.2
```

Play needs to adjust some code for its next major release to correctly support Jackson 2,17, see: https://github.com/playframework/playframework/pull/12440

Co-authored-by: Matthias Kurz <m.kurz@irregular.at>