Get rid of compilation warnings with latest version of closure-compiler
Closure-compiler is used to compile and optimise the JavaScript from the twirl templates. After updating to the latest version, tests started failing because the compiler would now throw warnigns like

```
java.lang.RuntimeException: JSC_INEXISTENT_PROPERTY. Property length never defined on Array<?> at raf.js line 12 : 35}
[info]   at common.JsMinifier$.compileUnsafe(JsMinifier.scala:66)
[info]   at common.JsMinifier$.$anonfun$unsafeCompileWithStandardOptimisation$1(JsMinifier.scala:76)
[info]   at scala.util.Try$.apply(Try.scala:210)
[info]   at common.JsMinifier$.unsafeCompileWithStandardOptimisation(JsMinifier.scala:76)
[info]   at common.InlineJs$.optimizeJs(JsMinifier.scala:108)
```

even though `length` is clearly a property of `Array`!

It turns out the compiler has become stricter in type checking and expects from the developer to be very explicit about the objects being window objects and initialise them  with code like `var myArray = new window.Array('ms', 'moz', 'webkit', 'o')` instead of `var myArray = ['ms', 'moz', 'webkit', 'o']`.

Co-authored-by: JamieB-gu<53781962+JamieB-gu@users.noreply.github.com>
Co-authored-by: Alex Sanders<alex.sanders@guardian.co.uk>